import os
import json
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate

def build_chat_chain(report: dict):
    context = json.dumps(report, indent=2)
    # Escape curly braces so LangChain doesn't interpret them as variables
    context = context.replace("{", "{{").replace("}", "}}")
    
    llm = ChatGroq(
        model="llama-3.3-70b-versatile",
        temperature=0.5,
        max_tokens=1024,
        groq_api_key=os.getenv("GROQ_API_KEY", "")
    )
    
    system_prompt = f"""You are a helpful intelligence analyst assistant.
You have access to the latest automated news report generated by the GenAI Report Agent.

=== LATEST REPORT CONTEXT ===
{context}
=== END OF REPORT CONTEXT ===

Instructions:
- Always ground your answers in the report above.
- If the user asks vague questions like "What's happening?",
  summarise the key findings from the report.
- Do not hallucinate facts not present in the report."""
    
    chain = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("system", "Previous conversation:\n{history}"),
        ("human", "{question}"),
    ]) | llm
    
    return chain
